# Generated by Django 2.2 on 2021-04-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210429_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='course',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='student',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
