# Generated by Django 3.2 on 2021-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210428_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='currentcourses',
            name='courses',
        ),
        migrations.AddField(
            model_name='currentcourses',
            name='courseId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentcourses',
            name='student',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
