# Generated by Django 3.2 on 2021-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
