# Generated by Django 3.2 on 2021-04-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
