# Generated by Django 3.2 on 2021-04-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentCourses',
        ),
    ]
