# Generated by Django 3.2 on 2021-04-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_currentcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='api.Course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentcourses', to='api.student')),
            ],
        ),
    ]
