# Generated by Django 3.2 on 2021-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210429_1527'),
        ('api', '0015_auto_20210430_1232'),
    ]

    operations = [
    ]
