# Generated by Django 3.2 on 2021-04-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_0006_auto_20210429_1527_0015_auto_20210430_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='MyCart',
        ),
        migrations.RemoveField(
            model_name='currentcourses',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='course',
        ),
        migrations.AddField(
            model_name='currentcourses',
            name='items',
            field=models.ManyToManyField(to='api.Course'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(null=True, to='api.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currentcourses',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentcourses', to='api.student'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='api.Course'),
        ),
        migrations.AddField(
            model_name='cart',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student'),
        ),
    ]
